Controllers/AreaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using STARPrueba.Models;
using Microsoft.EntityFrameworkCore;

namespace STARPrueba.Controllers
{
    public class AreaController : Controller
    {
        private readonly StarGroupContext Context;
        public AreaController(StarGroupContext context)
        {
            Context = context;
        }
        // GET: AreaController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Area = await Context.Areas.ToListAsync();
            return View(Area);
        }

        // GET: AreaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AreaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AreaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Area addarearequest)
        {
            try
            {
                var area = new Area()
                {
                    Nombre = addarearequest.Nombre,
                   
                    //IdCategoriaNavigationId = null
                };
                await Context.Areas.AddAsync(area);
                await Context.SaveChangesAsync();

                return RedirectToAction("Index");
                // return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AreaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AreaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AreaController/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Area area = Context.Areas.Find(id);
            return View(area);
        }

        // POST: AreaController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Area aut = Context.Areas.Find(id);
                Context.Areas.Remove(aut);
                Context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using STARPrueba.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace STARPrueba.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly StarGroupContext _context;
        public EmpleadoController(StarGroupContext context)
        {
            _context = context;
        }
        // GET: EmpleadoController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Empleado= await _context.Empleados.ToListAsync();
            return View(Empleado);
        }

        // GET: EmpleadoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmpleadoController/Create
        public ActionResult Create()
        {
            var drowArea = _context.Areas.ToList();
            ViewData["IdArea"] = (List<STARPrueba.Models.Area>)drowArea.ToList();
            return View();
        }

        // POST: EmpleadoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Empleado addempleadorequest)
        {
            try
            {
                var empleado = new Empleado()
                {
                    Nombre = addempleadorequest.Nombre,
                    ApePaterno = addempleadorequest.ApePaterno,
                    ApeMaterno = addempleadorequest.ApeMaterno,
                    Edad = addempleadorequest.Edad,
                    Direccion = addempleadorequest.Direccion,
                    Email = addempleadorequest.Email,
                    AreaId = addempleadorequest.AreaId,
                    //IdCategoriaNavigationId = null

                };
                await _context.Empleados.AddAsync(empleado);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpleadoController/Edit/5
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null || _context.Empleados == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(Id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: EmpleadoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("Id,Nombre,ApePaterno,ApeMaterno,Edad,Direccion,Email")] Empleado empleado)
        {
            if (id != empleado.Id)
            {
                return NotFound();
            }
            
               empleado.AreaId = 1;
               
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                  
                    return View();
                }
                return RedirectToAction(nameof(Index));
            //}
            return View(empleado);
        }
        //[HttpGet]
        //public IActionResult Edit(int? Id)
        //{
        //    if (Id == null)
        //    {
        //        return NotFound();
        //    }
        //    //GetById
        //    Empleado emplead = _context.Empleados.Find(Id);
        //    if (emplead == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(emplead);
        //}
        // GET: EmpleadoController/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Empleado empleado = _context.Empleados.Find(id);
            return View(empleado);
           
        }

        // POST: EmpleadoController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Empleado emp = _context.Empleados.Find(id);
                _context.Empleados.Remove(emp);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <title>@ViewData["Title"] - STARPrueba</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/STARPrueba.styles.css" asp-append-version="true" />*@

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/fontawesome.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assets/css/templatemo-sixteen.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assets/css/owl.css" asp-append-version="true" />
</head>

<body>
    @* <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  *@
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h2>STAR <em>GROUP</em></h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">*@
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home
                                <span class="sr-only">(current)</span>
                            </a>
                         
                        </li>
                        @*<li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                       @* </li>*@
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Area" asp-action="Index">AREAS</a> @*Products*@
                           @* <a class="nav-link text-dark" asp-area="" asp-controller="Area" asp-action="Index">AREA</a>*@
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Empleado" asp-action="Index">EMPLEADOS</a>
                           @* <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">EMPLEADOS</a>*@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
   @* <div class="page-heading about-heading header-text">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-content">
              <h4>about us</h4>
              <h2>our company</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - STARPrueba - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>